server.port: 8201
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/snowflake?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    # 默认的Mongodb服务器
    mongodb:
      database: dev.mongodb.i.sixi.com
      host: dev.mongodb.i.sixi.com
      port: 27017
  # 默认的Redis服务器 存储公共信息
  redis:
    database: 0
    host: 127.0.0.1
    port: 6397
    # 默认的RabbitMQ服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 500
        max-concurrency: 1000
        acknowledge-mode: MANUAL