server.port: ${zy-micro-services.ports.api-gateway:0}
spring:
  cloud:
    gateway:
      routes: #配置路由路径
      - id: demo_oauth
        uri: lb://demo-oauth-service
        predicates:
          - Path=/demo/auth/**
        filters:
          - StripPrefix=2
      - id: base_oauth
        uri: lb://base-oauth-service
        predicates:
          - Path=/auth/**
        filters:
          - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8091/rsa/publicKey' #配置RSA的公钥访问地址
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"